// <auto-generated />
using System;
using Back.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Back.Models.Bil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("bildePlassering")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("merke")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("modell")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("registreringsNummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("tilgjengelig")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Biler");
                });

            modelBuilder.Entity("Back.Models.Bruker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("etternavn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("fornavn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("førerkortNummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Brukere");
                });

            modelBuilder.Entity("Back.Models.Låneavtale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("førerkortNummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("registreringsNummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("sluttDato")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("startDato")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Låneavtaler");
                });
#pragma warning restore 612, 618
        }
    }
}
